version: '3'
services: 
  db:
    image: mongo
    ports: 
      - "27018:27017"
    networks: 
      - app_network
    volumes:
      - .docker/data/db:/data/db
    restart: unless-stopped
  web: 
    build: .
    environment: 
      - DB_CONNECTION=mongodb://db:27017/cryptocurrency
    ports:
      - "8080:8080"
    networks: 
      - app_network
    depends_on: 
      - db
    restart: unless-stopped
networks: 
  app_network:
    driver: bridge

