version: '3'
services: 
  db:
    image: mongo
    ports: 
      - "27018:27017"
    networks: 
      - app_network
    volumes:
      - .docker/data/db:/data/db
  web: 
    build: .
    ports:
      - "8080:8080"
    networks: 
      - app_network
    depends_on: 
      - db
networks: 
  app_network:
    driver: bridge

